### ISSUE TITLE
IM, Failure tolerance & correct reconnect logic

### ISSUE THREAD

**Issue by LeonLiuY** [rhinobird-io/rhinobird-web#105]
Currently IM misses messages if websocket connection is not stable.

And after user reconnect to server, they can not receive messages.

**Comment by zycbobby** [comment]
When socket fails
- Send function failed
- Change channel function failed

**Comment by zycbobby** [comment]
@liuyang1204 Can this one be closed?

**Comment by LeonLiuY** [comment]
I think so
