### ISSUE TITLE
IM unread message not set to read after refresh

### ISSUE THREAD

**Issue by LeonLiuY** [rhinobird-io/rhinobird-web#113]
Channel still show unread, even after refresh

**Comment by LeonLiuY** [comment]
@zycbobby  Found this issue still exists in newest production env

**Comment by zycbobby** [comment]
Reproduce:
1. Create unread message in channel(e.g. team_3)
2. Reload whole page to other channel (e.g. team_2), make MessageStore._messages re-construct
3. Click team_3
4. Go to team_2
5. Reload whole page to team_2

Bugs happen
