### ISSUE TITLE
URL contains .. can't be parsed correctly in IM 

### ISSUE THREAD

**Issue by liyuankui** [rhinobird-io/rhinobird-web#126]
e.g., http://172.26.142.48/viewerjs/#../0529/slides.pdf

**Comment by LeonLiuY** [comment]
This issue is related with the library we used, [markdown-it](https://github.com/markdown-it/markdown-it).

I've commented an issue:

https://github.com/markdown-it/linkify-it/issues/15#issuecomment-110201951

**Comment by puzrin** [comment]
I've released update of linkify-it. If you reinstall dependencies properly, this bug will be fixed.

https://github.com/markdown-it/linkify-it/commit/08f53f44e489927f57409b5f063bde4a4ce0f575

**Comment by LeonLiuY** [comment]
@puzrin Great, thanks for quick help

**Comment by LeonLiuY** [comment]
Solved, close this issue.
