### ISSUE TITLE
Want, 'TIME settings' in the 'Point' type event.

### ISSUE THREAD

**Issue by e99h2121** [rhinobird-io/rhinobird-web#155]
On the operation of Create Event in Calendar:
Even in choosing the 'Point' type's event, I'd like to set the TIME. (It means not only the DATE, but also)

**Comment by LeonLiuY** [comment]
This is a bug, we intended to allow TIME in `pointed` event. And now it is fixed, please wait for next deployment

**Comment by LeonLiuY** [comment]
Already fixed.
