### ISSUE TITLE
Material-UI's less files are deprecated now

### ISSUE THREAD

**Issue by wizawu** [rhinobird-io/rhinobird-web#57]
@zycbobby @RonaldoLee @liuyang1204 

See [0.8.0 change log](https://github.com/callemall/material-ui/blob/2eb14e69c411e9165d696df1a88d4ac8036591bf/CHANGELOG.md#080-pre-release).

Any countermeasure can be discussed here.

**Comment by LeonLiuY** [comment]
We've migrated
